using System;
using System.Collections.Generic;
using System.Globalization;

namespace DiskHawk.Core
{
    /// <summary>
    /// UI language. UI strings in the source code are written in Turkish and used as keys;
    /// when English (default) is selected the translation is returned from this dictionary.
    /// Adding a language only requires another dictionary with the same structure.
    /// </summary>
    public static class L
    {
        /// <summary>"en" (default) or "tr".</summary>
        public static string Lang = "en";

        public static bool IsTurkish { get { return Lang == "tr"; } }

        public static string T(string tr)
        {
            if (tr == null || Lang == "tr") return tr;
            string en;
            return En.TryGetValue(tr, out en) ? en : tr;
        }

        public static string F(string tr, params object[] args)
        {
            return string.Format(CultureInfo.CurrentCulture, T(tr), args);
        }

        /// <summary>"tr" if the operating system language is Turkish, otherwise "en".</summary>
        public static string SystemDefault
        {
            get { return CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == "tr" ? "tr" : "en"; }
        }

        private static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            { "Active Directory'den makine getir", "Import machines from Active Directory" },
            { "Devre dışı hesapları atla", "Skip disabled computer accounts" },
            { "İsim filtresi:", "Name filter:" },
            { "OU (isteğe bağlı):", "OU (optional):" },
            { "gün içinde oturum açmış olanlar (0 = hepsi)", "days since last logon (0 = all)" },
            { "Son aktiflik:", "Last active:" },
            { "Örnek filtre: IST-*  |  OU örneği: OU=Istanbul,OU=Computers,DC=contoso,DC=local", "Filter example: NYC-*  |  OU example: OU=NewYork,OU=Computers,DC=contoso,DC=local" },
            { "Vazgeç", "Cancel" },
            { "Listeye ekle", "Add to list" },
            { "Sorgula", "Search" },
            { "Sorgulanıyor...", "Searching..." },
            { "AD sorgusu başarısız:\n", "Active Directory query failed:\n" },
            { " makine bulundu", " machines found" },
            { "Zaman;Yapan;Konsol;Makine;Tür;Yol;Beklenen (MB);Sonuç;Boşalan (MB);Silinen dosya;Silinemeyen dosya;Açıklama", "Time;User;Console;Machine;Type;Path;Expected (MB);Result;Freed (MB);Files deleted;Files not deleted;Details" },
            { "Klasör", "Folder" },
            { "Dosya", "File" },
            { "Kalıcı silme onayı - ", "Confirm permanent deletion - " },
            { " üzerinde KALICI silme", ": PERMANENT deletion" },
            { "Aşağıdaki öğeler hedef makinenin kendisinde silinecek. Geri Dönüşüm Kutusu kullanılmaz, geri alınamaz.\n", "The items below will be deleted on the target machine itself. The Recycle Bin is not used; this cannot be undone.\n" },
            { "Açık / kilitli dosyalar atlanır ve sonuçta raporlanır. Her işlem denetim kaydına yazılır.", "Open or locked files are skipped and reported. Every operation is written to the audit log." },
            { "Durum", "Status" },
            { "Tür", "Type" },
            { "Boyut", "Size" },
            { "Yol", "Path" },
            { "Not", "Note" },
            { "Silinmez", "Never deleted" },
            { "KRİTİK", "CRITICAL" },
            { "Silinecek", "Will be deleted" },
            { "Bu işlemin geri alınamayacağını anlıyorum", "I understand this cannot be undone" },
            { " KRİTİK sistem/profil yolunu da sil (makine açılmayabilir / kullanıcı verisi gider)", " CRITICAL system/profile path(s) too (machine may not boot / user data will be lost)" },
            { "Kalıcı olarak sil  ({0} öğe, {1})", "Delete permanently  ({0} items, {1})" },
            { "Silinecek: {0} öğe, {1}, ~{2} dosya{3}", "To delete: {0} items, {1}, ~{2} files{3}" },
            { " öğe atlanacak", " items will be skipped" },
            { " öğe (sürücü kökü / geçersiz yol) hiçbir durumda silinmez", " item(s) (drive root / invalid path) are never deleted" },
            { "Silme sonucu - ", "Deletion result - " },
            { "Boşalan alan: ", "Space freed: " },
            { "Silindi: {0}   |   Kısmen: {1}   |   Silinemedi: {2}   |   Korunuyor: {3}   |   Zaten yok: {4}", "Deleted: {0}   |   Partial: {1}   |   Failed: {2}   |   Protected: {3}   |   Already gone: {4}" },
            { "Sonuç", "Result" },
            { "Boşalan", "Freed" },
            { "Silinen", "Deleted" },
            { "Silinemeyen", "Not deleted" },
            { "Açıklama", "Details" },
            { "Kopyala", "Copy" },
            { "Kapat", "Close" },
            { "Denetim kaydını göster", "Show audit log" },
            { "Hazır. Veri klasörü: ", "Ready. Data folder: " },
            { "UYARI: ", "WARNING: " },
            { " bulunamadı - uzak tarama yapılamaz.", " not found - remote scanning is unavailable." },
            { "UYARI: Uygulama yönetici olarak çalışmıyor; yerel taramada bazı klasörler okunamayabilir.", "WARNING: Not running as administrator; the fast MFT engine is unavailable for local scans and some folders may be unreadable." },
            { "Ekle", "Add" },
            { "Tümü", "All" },
            { "Tamam", "OK" },
            { "Hata", "Failed" },
            { "Çalışan / kuyrukta", "Running / queued" },
            { "Taranmamış", "Not scanned" },
            { "%90+ dolu", "90%+ full" },
            { "%80+ dolu", "80%+ full" },
            { "Makine", "Machine" },
            { "Sürücü", "Drive" },
            { "Boş", "Free" },
            { "Doluluk", "Usage" },
            { "Sıcak nokta (yerin yoğunlaştığı klasör)", "Hotspot (where the space is concentrated)" },
            { "S.N. boyut", "Hotspot size" },
            { "En büyük dosya", "Largest file" },
            { "Son tarama", "Last scan" },
            { "Mesaj", "Message" },
            { "Sonucu aç", "Open result" },
            { "Tara", "Scan" },
            { "C$ paylaşımını aç", "Open C$ share" },
            { "Sonuç klasörünü aç", "Open report folder" },
            { "Makine adlarını kopyala", "Copy machine names" },
            { "Mesajı kopyala", "Copy message" },
            { "Listeden kaldır", "Remove from list" },
            { "Devam eden taramalar var. İptal edilip çıkılsın mı?", "Scans are still running. Cancel them and exit?" },
            { "   - kapatılıyor, uzak taramalar sonlandırılıyor...", "   - closing, stopping remote scans..." },
            { "Panodan ", "From clipboard: " },
            { " makine eklendi.", " machines added." },
            { "Metin / CSV (*.txt;*.csv)|*.txt;*.csv|Tüm dosyalar (*.*)|*.*", "Text / CSV (*.txt;*.csv)|*.txt;*.csv|All files (*.*)|*.*" },
            { "Makine listesi", "Machine list" },
            { "AD: ", "AD: " },
            { " makine bulundu, ", " machines found, " },
            { " yeni eklendi.", " new added." },
            { " makine listeden kaldırılsın mı? (rapor dosyaları silinmez)", " machines will be removed from the list. Continue? (report files are kept)" },
            { "Tarayıcı bulunamadı:\n", "Scanner not found:\n" },
            { "\n\nDiskHawk.Scanner.exe bu uygulamayla aynı klasörde olmalı.", "\n\nDiskHawk.Scanner.exe must be in the same folder as this application." },
            { " makine kuyruğa alındı.", " machines queued." },
            { "İptal edildi", "Cancelled" },
            { "Durduruluyor... (", "Stopping... (" },
            { " kuyruktaki iş iptal, çalışanlar sonlandırılıyor)", " queued jobs cancelled, running scans are being terminated)" },
            { "Başlıyor", "Starting" },
            { "  (tekrar denenecek)", "  (will retry)" },
            { " - tekrar denenecek", " - will retry" },
            { ": HATA - ", ": ERROR - " },
            { "Yerel tarama zaten çalışıyor.", "A local scan is already running." },
            { "Sabit disk bulunamadı.", "No fixed drives found." },
            { "Yerel tarama başladı: ", "Local scan started: " },
            { "Yerel tarama hatası: ", "Local scan error: " },
            { "Yerel tarama başarısız:\n", "Local scan failed:\n" },
            { "  {0}: {1} motor, {2}{3}", "  {0}: {1} engine, {2}{3}" },
            { "  (MFT kullanılamadı: ", "  (MFT unavailable: " },
            { "Yerel tarama bitti: ", "Local scan finished: " },
            { " sıcak nokta ", " hotspot " },
            { " için henüz rapor yok. Önce tarayın.", " has no report yet. Scan it first." },
            { "Toplam (GB)", "Total (GB)" },
            { "Boş (GB)", "Free (GB)" },
            { "Doluluk (%)", "Usage (%)" },
            { "Taranan (GB)", "Scanned (GB)" },
            { "Dosya sayısı", "File count" },
            { "Sıcak nokta", "Hotspot" },
            { "Sıcak nokta (GB)", "Hotspot (GB)" },
            { "En çok dosya olan klasör", "Folder with most files" },
            { "En büyük dosya (MB)", "Largest file (MB)" },
            { "Bulutta (GB)", "Cloud-only (GB)" },
            { "Erişilemeyen klasör", "Inaccessible folders" },
            { "Özet CSV yazıldı: ", "Summary CSV written: " },
            { " satır)", " rows)" },
            { "Yerel tarama: {0}  {1} dosya  {2}  {3}", "Local scan: {0}  {1} files  {2}  {3}" },
            { "disk_ozet_", "disk_summary_" },
            { "Beklenmeyen hata:\n\n", "Unexpected error:\n\n" },
            { "\n\nDetay veri klasöründeki error.log dosyasına yazıldı.", "\n\nDetails were written to error.log in the data folder." },
            { "Kuyrukta", "Queued" },
            { "Çalışıyor", "Running" },
            { "İptal", "Cancelled" },
            { "Önceki sonuç", "Previous result" },
            { "Ping ve SMB (445) yanıt vermedi (kapalı / ağda değil)", "No response to ping or SMB (445) (offline / not on network)" },
            { "WMI bağlanıyor", "Connecting WMI" },
            { "Kopyalanıyor", "Copying" },
            { "Başlatılıyor", "Launching" },
            { ": tarayıcı başlatıldı (PID ", ": scanner started (PID " },
            { "Tarayıcı hatası: ", "Scanner error: " },
            { "Tarayıcı beklenmedik şekilde kapandı (AV/AppLocker engellemiş olabilir)", "Scanner exited unexpectedly (possibly blocked by AV/AppLocker)" },
            { "Zaman aşımı (", "Timeout (" },
            { " dk)", " min)" },
            { "Rapor alınıyor", "Retrieving report" },
            { "{0}: tamam - {1} ({2})", "{0}: done - {1} ({2})" },
            { " dolu, sıcak nokta ", " full, hotspot " },
            { ", motor ", ", engine " },
            { "sürücü yok", "no drives" },
            { "Siliniyor", "Deleting" },
            { ": silme başlatıldı (PID ", ": deletion started (PID " },
            { " öğe)", " items)" },
            { "Silme hatası: ", "Deletion error: " },
            { "Siliniyor: {0} dosya, {1} boşaldı", "Deleting: {0} files, {1} freed" },
            { "Tarayıcı beklenmedik şekilde kapandı; silme kısmen yapılmış olabilir, makineyi yeniden tarayın", "Scanner exited unexpectedly; deletion may be partial, rescan the machine" },
            { "Silme ", "Deletion reported no progress for " },
            { " dk boyunca ilerleme bildirmedi; uzak işlem hâlâ çalışıyor olabilir. Sonucu görmek için makineyi yeniden tarayın.", " min; the remote process may still be running. Rescan the machine to see the result." },
            { "WMI bağlantısı zaman aşımına uğradı (RPC/firewall engelli olabilir)", "WMI connection timed out (RPC/firewall may be blocking)" },
            { "Tarayıcı exe bulunamadı: ", "Scanner executable not found: " },
            { "Tarayıcı kopyalanamadı - makinede önceki bir tarama hâlâ çalışıyor olabilir", "Could not copy the scanner - a previous scan may still be running on the machine" },
            { "Uzak işlem başlatılamadı: ", "Could not start remote process: " },
            { "erişim reddedildi (2)", "access denied (2)" },
            { "yetersiz yetki (3)", "insufficient privilege (3)" },
            { "bilinmeyen hata (8)", "unknown failure (8)" },
            { "yol bulunamadı (9)", "path not found (9)" },
            { "geçersiz parametre (21)", "invalid parameter (21)" },
            { "kod ", "code " },
            { "Uzak işlem sonlandırılamadı: ", "Could not terminate remote process: " },
            { "Taranıyor (", "Scanning (" },
            { " sn)", " s)" },
            { "Taranıyor {0}  {1} dosya  {2}", "Scanning {0}  {1} files  {2}" },
            { "(detay yok)", "(no details)" },
            { ": erişim reddedildi (yetkili hesapla çalıştırın)", ": access denied (run with an administrative account)" },
            { "RPC sunucusu yok (makine kapalı, firewall veya WMI engelli)", "RPC server unavailable (machine offline, firewall or WMI blocked)" },
            { ": erişim reddedildi", ": access denied" },
            { "RPC çağrısı başarısız", "RPC call failed" },
            { "[bu klasördeki dosyalar]", "[files in this folder]" },
            { "CSV'ye aktar", "Export CSV" },
            { "Rapor dosyasını göster", "Show report file" },
            { "Klasörler", "Folders" },
            { "En büyük dosyalar", "Largest files" },
            { "Uzantılar", "Extensions" },
            { "Silme sürüyor, bitince pencereyi kapatabilirsiniz.", "Deletion in progress; you can close the window when it finishes." },
            { "Tarama: {0}   |   Tarayıcı v{1}   |   {2}   |   {3}", "Scanned: {0}   |   Scanner v{1}   |   {2}   |   {3}" },
            { "Sürücü:", "Drive:" },
            { "Toplam {0}  |  Boş {1}  ({2} dolu)", "Total {0}  |  Free {1}  ({2} used)" },
            { "Taranan {0}, {1} dosya, {2} klasör  |  {3}{4}", "Scanned {0}, {1} files, {2} folders  |  {3}{4}" },
            { "Erişilemeyen ", "Inaccessible: " },
            { " klasör", " folders" },
            { "Bulutta (diskte değil) ", "Cloud-only (not on disk) " },
            { "▲ Üst", "▲ Up" },
            { "Kök", "Root" },
            { "Ad", "Name" },
            { "Pay", "Share" },
            { "Son değişiklik", "Last modified" },
            { "Aç", "Open" },
            { "Yolu kopyala", "Copy path" },
            { "Explorer'da aç", "Open in Explorer" },
            { "Kalıcı olarak sil...", "Delete permanently..." },
            { "Erişim yok", "No access" },
            { "Okuma hatası", "Read error" },
            { "Filtre:", "Filter:" },
            { "Klasöre git", "Go to folder" },
            { "Explorer'da göster", "Show in Explorer" },
            { "{0} dosya, toplam {1}   (rapora {2} üstü en büyük dosyalar alınır)", "{0} files, total {1}   (the report keeps the largest files above {2})" },
            { "Uzantı", "Extension" },
            { "Ortalama boyut", "Average size" },
            { "(uzantısız)", "(no extension)" },
            { "Bu uzantıdaki en büyük dosyaları göster", "Show largest files with this extension" },
            { "[bu klasördeki dosyalar] satırı toplu silinemez.\nDosyaları 'En büyük dosyalar' sekmesinden seçip silebilirsiniz.", "The [files in this folder] row cannot be deleted as a whole.\nSelect the files on the 'Largest files' tab instead." },
            { "Siliniyor (", "Deleting (" },
            { "yerel", "local" },
            { "başlıyor", "starting" },
            { " öğe için kalıcı silme başlatıldı", " item(s): permanent deletion started" },
            { ": silme yapılamadı - ", ": deletion failed - " },
            { "Silme yapılamadı:\n", "Deletion failed:\n" },
            { "{0}: silme bitti - {1} öğe, {2} boşaldı", "{0}: deletion finished - {1} items, {2} freed" },
            { "Rapor güncellenemedi: ", "Could not update report: " },
            { "CSV dosyalarının yazılacağı klasör", "Folder for the CSV files" },
            { "CSV yazılamadı:\n", "Could not write CSV:\n" },
            { "Rapor açılamadı: ", "Could not open report: " },
            { "Rapor açılamadı:\n", "Could not open report:\n" },
            { "Bu klasörde veri yok", "No data in this folder" },
            { "[dosyalar]", "[files]" },
            { "\n[bu klasördeki dosyalar]\n", "\n[files in this folder]\n" },
            { " dosya", " files" },
            { " dosya, ", " files, " },
            { "_klasorler.csv", "_folders.csv" },
            { "Derinlik", "Depth" },
            { "Boyut (MB)", "Size (MB)" },
            { "Alt klasör", "Subfolders" },
            { "Klasördeki dosyalar (MB)", "Files in folder (MB)" },
            { "_dosyalar.csv", "_files.csv" },
            { "_uzantilar.csv", "_extensions.csv" },
            { "rapor", "report" },
            { "Silindi", "Deleted" },
            { "Kısmen silindi", "Partially deleted" },
            { "Korunuyor", "Protected" },
            { "Zaten yok", "Already gone" },
            { "Sonuç bilinmiyor", "Result unknown" },
            { "Silinemedi", "Failed" },
            { " (kritik yol onayı verilmedi)", " (critical path not confirmed)" },
            { "Boş yol", "Empty path" },
            { "Tam yerel yol değil (X:\\... bekleniyor)", "Not a full local path (X:\\... expected)" },
            { "Geçersiz yol", "Invalid path" },
            { "Sürücü kökü", "Drive root" },
            { "NTFS iç dosyası", "NTFS system file" },
            { " sistem klasörü", " system folder" },
            { "Windows sistem klasörü", "Windows system folder" },
            { "Sistem dosyası", "System file" },
            { "ProgramData kökü", "ProgramData root" },
            { "Users kökü", "Users root" },
            { "Varsayılan profil", "Default profile" },
            { "Kullanıcı profil klasörü (içindekiler silinebilir)", "User profile folder (its contents can be deleted)" },
            { "Profilin sistem klasörü (içindekiler silinebilir)", "Profile system folder (its contents can be deleted)" },
            { "Kullanıcı kayıt defteri dosyası", "User registry hive" },
            { "OneDrive klasörü: silme buluta da yansır (OneDrive'da 'Alan boşalt' kullanın)", "OneDrive folder: deletions sync to the cloud (use 'Free up space' in OneDrive)" },
            { " klasörünün kendisi (içindekiler silinebilir)", " folder itself (its contents can be deleted)" },
            { "Bulut / özel öğe atlandı (OneDrive vb.)", "Cloud / special item skipped (OneDrive etc.)" },
            { ": bulut / özel öğe atlandı", ": cloud / special item skipped" },
            { " dosya silinemedi. ", " files could not be deleted. " },
            { "Bulunamadı", "Not found" },
            { "Erişim reddedildi", "Access denied" },
            { "Dosya kullanımda (açık)", "File in use (open)" },
            { "Dosyanın bir kısmı kilitli", "Part of the file is locked" },
            { "Klasör boş değil (silinemeyen dosyalar var)", "Folder not empty (some files could not be deleted)" },
            { "Yol çok uzun", "Path too long" },
            { "Win32 hata ", "Win32 error " },
            { "Gerçek yol doğrulanamadı: ", "Could not verify the real path: " },
            { "Yol reddedildi: gerçek konum farklı (junction / bağlantı / kısa ad) → ", "Path rejected: real location differs (junction / link / short name) → " },
            { "MFT motoru kullanılamadı: ", "MFT engine unavailable: " },
            { " sn", " s" },
            { "{0} dk {1} sn", "{0} min {1} s" },
            { "{0} sa {1} dk", "{0} h {1} min" },
            { "dd.MM.yyyy HH:mm", "yyyy-MM-dd HH:mm" },
            { "Volume açılamadı (", "Could not open volume (" },
            { ") - yönetici yetkisi gerekli", ") - administrator rights required" },
            { "Konumlanamadı (", "Seek failed (" },
            { "Okuma hatası (", "Read error (" },
            { "Windows değil", "Not Windows" },
            { "Sürücü kökü değil", "Not a drive root" },
            { "NTFS değil (", "Not NTFS (" },
            { "NTFS boot sektörü değil", "Not an NTFS boot sector" },
            { "NTFS geometrisi geçersiz", "Invalid NTFS geometry" },
            { "$MFT boyutu geçersiz", "Invalid $MFT size" },
            { "$MFT okunamadı: ", "Could not read $MFT: " },
            { "$MFT {0} MB, {1:N0} kayıt; okunan {2} MB ({3}/{4} blok), {5} okuyucu; okuma+işleme {6} ms, ağaç {7} ms", "$MFT {0} MB, {1:N0} records; read {2} MB ({3}/{4} blocks), {5} readers; read+parse {6} ms, tree {7} ms" },
            { "$MFT kaydı okunamadı", "Could not read the $MFT record" },
            { "$MFT $DATA bulunamadı", "$MFT $DATA not found" },
            { "Desteklenmeyen dosya sürümü: ", "Unsupported report version: " },
            { "(yönetici değil)", "(not administrator)" },
            { "Ajan gerektirmez: WMI + SMB ile uzak tarama", "Agentless: remote scanning over WMI + SMB" },
            { "Ayarlar", "Settings" },
            { "Ayarlar kaydedildi.", "Settings saved." },
            { "Başarısız", "Failed" },
            { "Bu bilgisayar", "This PC" },
            { "Bu bilgisayarı tara", "Scan this computer" },
            { "Dil değişikliği uygulamayı yeniden başlatınca geçerli olur. Şimdi yeniden başlatılsın mı?", "The language change takes effect after a restart. Restart now?" },
            { "Dil:", "Language:" },
            { "Durdur", "Stop" },
            { "Durum:", "Status:" },
            { "Düşük disk önceliği (kullanıcıyı en az etkiler, daha yavaş)", "Low disk priority (minimal user impact, slower)" },
            { "En büyük dosyalar:", "Largest files:" },
            { "Etkinlik günlüğü", "Activity log" },
            { "Filo disk analizi", "Fleet Disk Analytics" },
            { "Genel", "General" },
            { "Görünen makinelerin özetini CSV olarak kaydet", "Save a summary of the visible machines as CSV" },
            { "Görünenleri tara", "Scan visible" },
            { "Hakkında", "About" },
            { "Ham NTFS $MFT motoru: sürücü başına saniyeler", "Raw NTFS $MFT engine: seconds per drive" },
            { "Hatalıları tekrar dene", "Retry failed" },
            { "Kaydet", "Save" },
            { "Klasörü aç", "Open folder" },
            { "Korumalı uzak silme ve denetim kaydı", "Guarded remote cleanup with audit trail" },
            { "Kritik (%90+ dolu)", "Critical (90%+ full)" },
            { "MB ve üstü dosyalar listelenir", "MB and larger files are listed" },
            { "Makine adı yazın ya da liste yapıştırın", "Type a machine name or paste a list" },
            { "Makine, mesaj ya da sıcak nokta ara (Ctrl+F)", "Search machine, message or hotspot (Ctrl+F)" },
            { "Makineler", "Machines" },
            { "Paralel tarama:", "Parallel scans:" },
            { "Rapor", "Report" },
            { "Rapor aç", "Open report" },
            { "Raporu olan", "With report" },
            { "Seçilileri tara", "Scan selected" },
            { "Sürüm", "Version" },
            { "TXT / CSV dosyasından makine listesi", "Machine list from a TXT / CSV file" },
            { "Tek konsoldan binlerce makine", "Thousands of machines from one console" },
            { "Tekrar deneme:", "Retries:" },
            { "Tüm hakları saklıdır.", "All rights reserved." },
            { "Uyarı (%80+ dolu)", "Warning (80%+ full)" },
            { "Uzak tarama", "Remote scanning" },
            { "Veri klasörü", "Data folder" },
            { "Windows ağlarında disk kullanımını hızla analiz eder ve güvenle temizler.", "Analyzes disk usage across Windows networks in seconds and cleans it up safely." },
            { "Zaman aşımı:", "Timeout:" },
            { "aynı anda taranan makine", "machines scanned at once" },
            { "dakika / makine", "minutes per machine" },
            { "geçici hatalarda", "on transient errors" },
            { "{0} / {1} makine gösteriliyor   |   Bu oturumda: {2} tamam, {3} hata   |   Paralel {4}, zaman aşımı {5} dk", "Showing {0} of {1} machines   |   This session: {2} done, {3} failed   |   Parallel {4}, timeout {5} min" },
            { "Önce ping / SMB erişilebilirliğini kontrol et", "Check ping / SMB reachability first" },
            { "Özet CSV", "Summary CSV" },
            { "İçe aktar", "Import" },
            { "Üst klasör", "Up" },
            { "Klasik", "Classic" },
            { "Dosyalar", "Files" },
            { "Alt klasörler", "Subfolders" },
            // 1.3.1 security hardening
            { "Bu yol açılamıyor (geçersiz karakter içeriyor).", "This path cannot be opened (it contains invalid characters)." },
            { "Hedef makine adı bilinmiyor veya geçersiz; yol açılamıyor.", "The target machine name is unknown or invalid; the path cannot be opened." },
            { "Bu yol başka bir sunucuya bağlanır: \\\\{0}\n\nWindows bu sunucuya kimlik bilgilerinizle bağlanır. Yalnızca güvendiğiniz sunucular için devam edin. Açılsın mı?", "This path connects to another server: \\\\{0}\n\nWindows will connect to this server with your credentials. Continue only for servers you trust. Open it?" },
            { "Bu yol açılamıyor (yerel sürücü yolu değil).", "This path cannot be opened (not a local drive path)." },
            { "Geçersiz makine adları atlandı (boşluk veya \\ / : * ? \" < > | ; , içeremez): ", "Invalid machine names skipped (no spaces or \\ / : * ? \" < > | ; ,): " },
            { "Silme listesinde geçersiz karakter içeren yol var; işlem yapılmadı.", "The deletion list contains a path with invalid characters; nothing was done." },
            { "Uzak çalışma klasörü bir bağlantı (junction/symlink); güvenli değil: ", "The remote working folder is a link (junction/symlink) and is not safe: " },
            { ": izinler ayarlanamadı - ", ": permissions could not be set - " },
            { "Uzak çalışma klasörü güvenli değil (yönetici olmayanların yazma izni var): ", "The remote working folder is not safe (non-administrators can write to it): " },
            { "Uzak çalışma klasörü zaten var (beklenmedik)", "The remote working folder already exists (unexpected)" },
            { "Tarayıcı kopyalanamadı: ", "Could not copy the scanner: " },
            { "Uzak makinedeki tarayıcı kopyası doğrulanamadı (dosya değiştirilmiş; güvenlik yazılımı müdahale etmiş olabilir)", "The scanner copy on the remote machine failed verification (the file was changed; security software may have interfered)" },
            { "Rapordaki makine adı geçersiz; bu rapor üzerinden uzak işlem yapılamaz.", "The machine name in this report is invalid; remote actions are not possible from this report." },
            { "Bu rapor bir dosyadan açıldı; hedef makine adı rapor dosyasından alınıyor: {0}\n\nRapor güvenilir bir kaynaktan geldiyse devam edin. Bu makineye bağlanılsın mı?", "This report was opened from a file; the target machine name is taken from the report file: {0}\n\nContinue only if the report came from a trusted source. Connect to this machine?" },
            { ": sonuç dosyasında istenmeyen yollar vardı, yok sayıldı", ": the result file contained paths that were not requested; they were ignored" },
            { "Rapor dosyası bozuk veya geçersiz: ", "The report file is corrupt or invalid: " },
            { "Geçerli bir DiskHawk raporu değil: ", "Not a valid DiskHawk report: " },
            { "Rapor dosyası bozuk (metin uzunluğu)", "The report file is corrupt (text length)" },
            { "Rapor dosyası bozuk (metin çok uzun)", "The report file is corrupt (text too long)" },
            { "Rapor dosyası bozuk ({0} sayısı: {1})", "The report file is corrupt ({0} count: {1})" },
            { "Rapor dosyası geçersiz kök yol içeriyor: ", "The report file contains an invalid root path: " },
            { "sürücü", "drive" },
            { "Rapor dosyası bozuk (klasör derinliği çok fazla)", "The report file is corrupt (folder depth too large)" },
            { "dosya", "file" },
            { "uzantı", "extension" },
            { "Rapor dosyası çok fazla klasör içeriyor (bozuk veya güvenilmez dosya)", "The report file contains too many folders (corrupt or untrusted file)" },
            { "Rapor dosyası bozuk (negatif alt klasör sayısı)", "The report file is corrupt (negative subfolder count)" },
            { "$MFT boyutu birim boyutundan büyük (bozuk birim)", "$MFT is larger than the volume (corrupt volume)" },
            { "$MFT attribute list bozuk", "$MFT attribute list is corrupt" },
            { "$MFT extent listesi bozuk", "$MFT extent list is corrupt" },
            { "Sonuç dosyasında bu yol için kayıt yok; makineyi yeniden tarayın", "The result file has no entry for this path; rescan the machine" },
            { "Yol geçersiz (kontrol karakteri içeriyor)", "Invalid path (contains control characters)" },
            { "Silme listesi başlığı bozuk", "The deletion list header is corrupt" },
            { "Silme listesi bozuk: {0} yol bekleniyordu, {1} satır var. Hiçbir şey silinmedi.", "The deletion list is corrupt: {0} paths expected, {1} lines found. Nothing was deleted." },
            // 1.3.3
            { "OU bir LDAP ayırt edici adı olmalı (örn. OU=Istanbul,OU=Computers,DC=contoso,DC=local); sunucu adı veya kaçışsız '/' içeremez.", "The OU must be an LDAP distinguished name (e.g. OU=Istanbul,OU=Computers,DC=contoso,DC=local); it cannot contain a server name or an unescaped '/'." },
            { "GÜVENLİK UYARISI: ", "SECURITY WARNING: " },
            { "Güvenlik uyarısı:\n\n", "Security warning:\n\n" },
            { "Bu konsol derlemesinde tarayıcının beklenen özeti yok; çözümü (tüm projeleri) yeniden derleyin.", "This console build has no expected scanner hash; rebuild the whole solution." },
            { "DiskHawk.Scanner.exe bu konsolla birlikte derlenen sürüm değil (dosya değiştirilmiş olabilir). Güvenlik için dağıtılmadı; uygulamayı güvenilir kaynaktan yeniden kurun veya derleyin.", "DiskHawk.Scanner.exe is not the version built with this console (the file may have been modified). It was not deployed for security reasons; reinstall or rebuild the application from a trusted source." },
            { "Tarayıcı dosyası doğrulanamadı: ", "Could not verify the scanner file: " },
            { "Uygulama klasörüne yönetici olmayan hesaplar yazabiliyor ({0}): {1}\nBu hesaplar tarayıcıyı değiştirip tüm makinelere dağıtılmasına yol açabilir. DiskHawk'ı yalnızca yöneticilerin yazabildiği bir klasöre (örn. C:\\Program Files\\DiskHawk) taşıyın.", "Non-administrator accounts can write to the application folder ({0}): {1}\nThey could replace the scanner that is deployed to all machines. Move DiskHawk to a folder only administrators can write to (e.g. C:\\Program Files\\DiskHawk)." },
            { "Uzak rapor dosyası beklenmedik kadar büyük ({0}); alınmadı.", "The remote report file is unexpectedly large ({0}); it was not retrieved." },
            { "Silme sonuç dosyası beklenmedik kadar büyük; okunmadı. Makineyi yeniden tarayın.", "The deletion result file is unexpectedly large and was not read. Rescan the machine." },
        };
    }
}
